[tools]
cargo-binstall = "1.21.1"
fd = "10.4.2"
glab = { version = "1.107.0", exe = "glab" }
go = "1.26.5"
hcloud = "1.66.0"
hk = "1.52.0"
node = "26.5.0"
pkl = "0.32.0"
python = "3.14.7"
prek = "0.4.10"
rclone = "1.75.0"
rust = "1.97.1"
steampipe = "2.4.4"
terraform-docs = "0.24.0"
tflint = "0.64.0"
ttyd = "1.7.7" # Dependency for vhs
usage = "5.1.0"
uv = "0.11.31"
vhs = "0.11.0"

###################################
# Python Packages - Managed by uv #
###################################
pipx = "latest"
"pipx:ansible" = { version = "14.2.0", uvx_args = "--with-executables-from ansible-core,ansible-lint" }
"pipx:jiratui" = "1.12.0"
"pipx:gnome-extensions-cli" = { version = "0.11.0", uvx_args = "--with pycairo,PyGObject" }
"pipx:pgcli" = "4.5.0"
"pipx:tldr" = "3.4.4"
"pipx:tofuref" = "1.8.1"
"pipx:wtfis" = "0.15.0"

##################
# Cargo Packages #
##################
"cargo:ag" = "0.19.5"
"cargo:mergiraf" = "0.18.0"
"cargo:onefetch" = "2.27.1"
"cargo:zeitfetch" = "0.1.16"

###############
# Go Packages #
###############
"go:github.com/walles/moor/v2/cmd/moor" = "2.15.2"

################
# NPM Packages #
################
"npm:gitlab-ci-local" = "4.74.0"

#################
# HTTP Packages #
#################
"github:alesbrelih/gitlab-ci-ls" = "1.3.4"
"github:aws-cloudformation/rain" = "1.24.4"
"github:bgreenwell/lstr" = "0.4.0"
"github:bluetuith-org/bluetuith" = "0.2.7"
"github:doy/rbw" = "1.15.0"
"github:ekzhang/bore" = "0.6.0"
"github:fioncat/otree" = "0.7.1"
"github:fish-shell/fish-shell" = "4.8.1"
"github:hupe1980/gotoaws" = "0.25.1"
"github:jacek-kurlit/pik" = "1.0.0"
"github:jbreckmckye/daylight" = "1.3.0"
"github:joschi/dive" = "0.14.0"
"github:unhappychoice/gittype" = "0.10.2"
"github:ynqa/sig" = "0.3.0"
"github:YS-L/flamelens" = "0.4.0"
"github:clawscli/claws" = "0.17.0"
"github:grafana/jsonnet-debugger" = "0.2.0"
"github:grafana/jsonnet-language-server" = "0.17.0"
"github:RasKrebs/sonar" = "0.4.0"

[settings]
pipx.uvx = true
pin = true
experimental = true

[settings.python]
uv_venv_auto = true

# We need to compile Python due to a Crypto error I currently cannot find. This might not be true anymore for the x64 system, so disabling.
# [settings.python]
# compile = true
