include:
  - project: el-capitano/tools/ci-cd-templates
    ref: v5.2.8
    file: '/pipelines/compliance/compliance.yml'

variables:
  ECG_VERIFY_SHELLCHECK_EXCLUDE_FILES: './chezmoi/private_dot_local/private_share/bash-completion/**/*'

stages:
  - verify
  - build
  - test
  - deploy
