include:
  - project: el-capitano/tools/ci-cd-templates
    ref: v4.6.4
    file: '/pipelines/compliance/compliance.yml'

variables:
  ECG_VERIFY_SHELLCHECK_EXCLUDE_FILES: './private_dot_local/**/*'

stages:
  - verify
  - build
  - test
  - deploy
