git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
gui:
  language: en
  sidePanels:
    - [files, stash, worktrees]
    - [commits, reflog]
    - [branches, remotes, tags]

