add_newline = true
format = "$fill\n$all$fill\n$character\n"

[directory]
truncate_to_repo = false
truncation_length = 8
truncation_symbol = "…/"

[env_var]
format = "TFENV: [$env_value]($style) "
style = "inverted bold bright-purple"
variable = "TF_VAR_env"

[fill]
style = "#33658A"
symbol = "-"

[git_commit]
only_detached = false
tag_disabled = false

[git_metrics]
disabled = false

[kubernetes]
disabled = false

[shlvl]
disabled = false
style = "inverted bold bright-purple"
threshold = 2

[terraform]
format = "via [Terraform $version]($style) "
