function hm() {
  pushd ~/dotfiles
  home-manager switch --flake .\#${1}
  popd
}

function g_commit_and_push() {
	local message="$1"
	git commit -am "${message}"
	git push
}

function g_setup_mr_branch() {
	local branch_name="$1"
	
	# Determine default branch on remote
	local default_branch="$(git remote show origin | sed -n '/HEAD branch/s/.*: //p')"
	
	# Make sure the default branch is up to date locally
	echo "default branch: '${default_branch}'. Updating default branch..."
	git fetch origin "${default_branch}":"${default_branch} --update-head-ok"
	
	git switch -c "${branch_name}" "${default_branch}"
	
	git push -u origin "${branch_name}"
	
	echo "Done!"
}

function aws_assume_role() {
	local role_arn="$1"
	export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s" \
	$(aws sts assume-role \
	--role-arn ${role_arn} \
	--role-session-name MySessionName \
	--query "Credentials.[AccessKeyId,SecretAccessKey,SessionToken]" \
	--output text))
}

function set_win_title(){
    echo -ne "\033]0; $(basename "$PWD") \007"
}
starship_precmd_user_func="set_win_title"

